### ISSUE TITLE
Sprint 1 checklist

### ISSUE THREAD

**Issue by Tanuj253** [Tanuj253/Tanuj_2025#1]
- [ ] Laptop Verification or cloud workspace: verification by linuz commands notebook
- [x] VSCode: live change code, commit, make, run localhost, test, debug
- [x] Show VSCode GitLens:  verify commits, show change, comments, reset to commit, run on old commit
- [x] Github student_2025 repo: template create, push changes, verify id, review analytics
- [ ] Github Pages Actions: review runs and verify runtimes, receive demo
- [x] Hacks Tools & Equipment Play: [Hacks](https://nighthawkcoders.github.io/portfolio_2025/jupyter/notebook/python#hacks)
- [ ] Hacks Github Pages Playground: [Hacks](https://nighthawkcoders.github.io/portfolio_2025/github/pages/hacks)
- [ ] Hacks SASS Basics: [Hacks](https://nighthawkcoders.github.io/portfolio_2025/sass_basics/play)
- [ ] Hacks Frontend: [Hacks](https://nighthawkcoders.github.io/portfolio_2025/frontend/basics/playground)
- [ ] Pair Programming: 
tangibles that show coop work
